### ISSUE TITLE
Make it more obvious how to produce overall constant survival mark.ces models

### ISSUE THREAD

**Issue by btohughhanmer** [btorobrob/cesr#5]
Might be useful sometimes to run an overall constant model survival estimate and compare it to the annual estimates but it wasn't immediately obvious to me how to do that! E.g in the reference guide say "...for example if you want to produce an overall survival survival estimate set compare to equal the number of capture intervals."

**Comment by btorobrob** [comment]
now menthioned in the help page, and in the vignette :)
